name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml

  build:
    name: ${{ matrix.platform }}
    needs: [ checks ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-x64
          - macos-arm
          - macos-x64
          - windows-x64

        include:
          - platform: linux-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - platform: macos-arm
            os: macos-15
            target: aarch64-apple-darwin
          - platform: macos-x64
            os: macos-13
            target: x86_64-apple-darwin
          - platform: windows-x64
            os: windows-2022
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          targets: ${{ matrix.target }}
          toolchain: stable

      - name: Install cargo-llvm-cov
        if: ${{ matrix.platform == 'linux-x64' }}
        uses: taiki-e/install-action@main
        with:
          tool: cargo-llvm-cov

      - name: Test
        if: ${{ matrix.platform != 'linux-x64' }}
        env:
          CARGO_TERM_COLOR: always
          RUST_BACKTRACE: 1
        run: |
          cargo test --workspace --all-features

      - name: Test with coverage
        if: ${{ matrix.platform == 'linux-x64' }}
        env:
          CARGO_TERM_COLOR: always
          RUST_BACKTRACE: 1
        run: |
          cargo llvm-cov --workspace --all-features --lcov --output-path lcov.info

      - name: Upload to codecov.io
        if: ${{ matrix.platform == 'linux-x64' }}
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
